enum MARKDOWN_LINKS {
    htmlCss = "/html-css",
    javaScript = "/java-script",
    python = "/python",
    nodeExpress = "/node-express",
    mongoDb = "/mongo-db",
    react = "/react",
    redux = "/redux",
    reactNative = "/react-native",
    dsa = "/dsa",
    hosting = "/hosting",
    systemDesign = "/system-design",
    git = "/git",
    sql = "/sql",
    microservice = "/microservice",
    docker = "/docker",
    kubernetes = "/kubernetes",
    messageBroker = "/message-broker",
    typeScript = "/type-script",
    nextJs = "/next-js",
    nestJs = "/nest-js",
    cleanCode = "/clean-code",
    others = "/others",
    graphQl = "/graph-ql",
}

export default MARKDOWN_LINKS;
