import MARKDOWN_LINKS from "./markdownLinks";

export const topics = [
    {
        href: MARKDOWN_LINKS.htmlCss,
        title: "HTML & CSS",
        icon: "/icon/html-css.png",
        description: "Docs for HTML & CSS",
    },
    {
        href: MARKDOWN_LINKS.javaScript,
        title: "JavaScript",
        icon: "/icon/js.png",
        description: "Docs for JavaScript",
    },
    {
        href: MARKDOWN_LINKS.python,
        title: "Python",
        icon: "/icon/python.webp",
        description: "Docs for Python",
    },
    {
        href: MARKDOWN_LINKS.nodeExpress,
        title: "Node & Express",
        icon: "/icon/node_express.jpg",
        description: "Docs for Node & Express",
    },
    {
        href: MARKDOWN_LINKS.mongoDb,
        title: "MongoDB",
        icon: "/icon/mongodb.jpeg",
        description: "Docs for MongoDB",
    },
    {
        href: MARKDOWN_LINKS.react,
        title: "React",
        icon: "/icon/ReactJS.png",
        description: "Docs for React",
    },
    {
        href: MARKDOWN_LINKS.redux,
        title: "Redux",
        icon: "/icon/redux.webp",
        description: "Docs for Redux",
    },
    {
        href: MARKDOWN_LINKS.reactNative,
        title: "React Native",
        icon: "/icon/react-native.png",
        description: "Docs for React Native",
    },
    {
        href: MARKDOWN_LINKS.dsa,
        title: "Data Structures & Algorithms",
        icon: "/icon/dsa.png",
        description: "Docs for DSA",
    },
    {
        href: MARKDOWN_LINKS.hosting,
        title: "Hosting",
        icon: "/icon/host.png",
        description: "Docs for Hosting",
    },
    {
        href: MARKDOWN_LINKS.systemDesign,
        title: "System Design",
        icon: "/icon/systom-design.webp",
        description: "Docs for System Design",
    },
    { href: MARKDOWN_LINKS.git, title: "Git", icon: "/icon/git.png", description: "Docs for Git" },
    { href: MARKDOWN_LINKS.sql, title: "SQL", icon: "/icon/postgres.webp", description: "Docs for SQL" },
    {
        href: MARKDOWN_LINKS.microservice,
        title: "Microservices",
        icon: "/icon/microservices.png",
        description: "Docs for Microservices",
    },
    {
        href: MARKDOWN_LINKS.docker,
        title: "Docker",
        icon: "/icon/Docker.png",
        description: "Docs for Docker",
    },
    {
        href: MARKDOWN_LINKS.kubernetes,
        title: "Kubernetes",
        icon: "/icon/kubernetes.jpg",
        description: "Docs for Kubernetes",
    },
    {
        href: MARKDOWN_LINKS.messageBroker,
        title: "Message Brokers",
        icon: "/icon/kafkavarabbit.jpg",
        description: "Docs for Message Brokers",
    },
    {
        href: MARKDOWN_LINKS.typeScript,
        title: "TypeScript",
        icon: "/icon/ts.png",
        description: "Docs for TypeScript",
    },
    {
        href: MARKDOWN_LINKS.nextJs,
        title: "Next.js",
        icon: "/icon/nextjs.png",
        description: "Docs for Next.js",
    },
    {
        href: MARKDOWN_LINKS.nestJs,
        title: "Nest.js",
        icon: "/icon/nestjs.png",
        description: "Docs for Nest.js",
    },
    {
        href: MARKDOWN_LINKS.cleanCode,
        title: "Clean Code",
        icon: "/icon/cleencode.jpg",
        description: "Docs for Clean Code",
    },
    {
        href: MARKDOWN_LINKS.graphQl,
        title: "GraphQL",
        icon: "/icon/GraphQL.png",
        description: "Docs for GraphQL",
    },
    {
        href: MARKDOWN_LINKS.typeOrm,
        title: "TypeORM",
        description: "Docs for TypeORM",
    },
    {
        href: MARKDOWN_LINKS.workflow,
        title: "Workflow",
        description: "Docs for Workflow",
    },
    {
        href: MARKDOWN_LINKS.others,
        title: "Others",
        icon: "/icon.png",
        description: "Miscellaneous Docs",
    },
];
